### ISSUE TITLE
Why are most of vim's shortcuts in prompt-toolkit?

### ISSUE THREAD

**Issue by lunemec** [jonathanslenders/pyvim#53]
I was trying to add some shortcuts, but I was wondering where are most shortcuts for pyvim. I found them all in python-prompt-toolkit, why is that? You want to provide vim-like shortcuts to all who use prompt-toolkit?

**Comment by SanketDG** [comment]
I don't know what you mean by shortcuts, but have a look at [key_bindings.py](https://github.com/jonathanslenders/pyvim/blob/master/pyvim/key_bindings.py). This may be what you are looking for.

`python-prompt-toolkit` is just a dependency for handling keyboard input.

**Comment by lunemec** [comment]
Oh I meant python-prompt-toolkit/key_binding/bindings/vi.py
There is a ton of common keyboard combinations specifically for vim ... I'm just wandering why are these in prompt-toolkit and not pyvim.. because when you want to edit or add some, you have to do this into another project...

**Comment by jonathanslenders** [comment]
The reason is that prompt-toolkit, in its core, is a kind of GNU readline replacement. Everything that readline does should be in there. And it happens that readline also implements a lot of Vi key bindings. (Especially the motion and text blocks commands.)

So, this is a conscious decision, to avoid code duplication.

**Comment by lunemec** [comment]
Thank you.
