### ISSUE TITLE
vi or vim clone?

### ISSUE THREAD

**Issue by niklasberglund** [jonathanslenders/pyvim#6]
README.rst says "A Vi clone in Python" but other text hint at it being a vim clone. Is this a vi or vim clone? I guess it's a typo in the README

**Comment by lunemec** [comment]
I think it is neither, Vi is the original program without extensions and it was supposed to be used with printers instead of monitor, while Vim supports plugins and other nice stuff. But pyvim has some additional features vim doesn't have when installed. So it is kind of like vim extended, or vim like editor ..

**Comment by jonathanslenders** [comment]
It's vim-like indeed. The goal is certainly not to create a perfect clone. But something that is useful and feels familiar for ``vim`` users.

**Comment by niklasberglund** [comment]
Rephrased in commit 2409ad7f4220f43340de87410601b5a029238a26
